anchors:
  env_gradle: &env_gradle
    docker:
      - image: cimg/openjdk:11.0
  restore_cache_wrapper: &restore_cache_wrapper
    restore_cache:
      key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_cache_deps: &restore_cache_deps
    restore_cache:
      keys:
        - gradle-deps2-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
        - gradle-deps2-
  set_git_origin_to_https: &set_git_origin_to_https
    run:
      name: set git origin to https
      command: git remote set-url --push origin https://github.com/diffplug/durian-rx
version: 2
jobs:
  # gradlew spotlessCheck assemble testClasses
  test: 
    <<: *env_gradle
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - run:
          name: gradlew check
          command: ./gradlew check --build-cache
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
  changelog_print:
    << : *env_gradle
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - run:
          name: gradlew changelogPrint
          command: ./gradlew changelogPrint
  do_release:
    << : *env_gradle
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - *set_git_origin_to_https
      - run:
          name: gradlew changelogPush
          command: ./gradlew changelogPush --stacktrace
workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - changelog_print:
          filters:
            branches:
              only: main
      - release:
          type: approval
          requires:
            - changelog_print
      - do_release:
          requires:
            - release
